import { useQuery, gql } from '@apollo/client';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import resellers from '../content/resellers.json'
import fs from 'fs'
const EXCHANGE_RATES = gql`
  query GetExchangeRates @api(contextKey: "apiName") {
    rates(currency: "USD") {
      currency
      rate
    }
  }
`;


// const EXCHANGE_RATES = gql`
//   query GetExchangeRates {
//     rates(currency: "USD") {
//       currency
//       rate
//     }
//   }
// `;


export default function Home() {
  const { loading, error, data }  = useQuery(EXCHANGE_RATES, { context: { apiName: "store1" } });
  // const { loading, error, data } = useQuery(EXCHANGE_RATES, { context: { apiName: "housings" } });
  // const { loading, error, data } = useQuery(EXCHANGE_RATES, {context: {clientName: 'endpoint2'}});
  // const { loading, error, data } = useQuery(EXCHANGE_RATES);
console.log("response", data)
console.log("resellers", resellers)

// var obj = require('file.json');
// obj.newThing = 'thing!';
// fs.writeFile('file.json', JSON.stringify(obj), function (err) {
//   console.log(err);
// });


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
